settings.mode='smart' # or 'html' or 'markdown' for normal wiki
settings.title='Ajay Maurya'
settings.subtitle='easy development'
settings.author='you'
settings.description=''
settings.keywords=''
settings.host_url='http://web2py.appspot.com'
settings.email_verification=False
settings.email_server='smtp.gmail.com:587'
settings.email_auth=None # or 'username:password'
settings.email_sender='you@gmail.com'
settings.administrator_emails=[]
